name: mock_supabase_http_client
description: A mock Supabase client for testing API calls without making actual http requests for Dart/Flutter apps that use Supabase.
version: 0.0.3+1
homepage: 'https://supabase.com'
repository: https://github.com/supabase-community/mock_supabase_http_client

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: '>=0.13.0 <2.0.0'
  supabase: ^2.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
